//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesAtt2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProducts
    {
        public int OrderID { get; set; }
        public string ProductsArticle { get; set; }
        public int ProductsCount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Products Products { get; set; }
    }
}
