//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesAtt2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public string ProductsTitle
        {
            get
            {
                return ProductsCategory + " | " + ProductsName;
            }
        }

       public string ProductsPhotoTrue
        {
            get
            {
                if (ProductsPhoto != null)
                {
                return "img/" + ProductsPhoto;

                }
                return null;
            }
        }

        public string Color
        {
            get
            {
                if (ProductsDiscount > 15)
                {
                    return "#2E8B57";
                }
                return "#FFFFFF";
            }
        }

        public string NoProductsColor
        {
            get
            {
                return ""; // цвет если нет продуктов на складе
            }
        }

        // перечеркнуть и высчитать обн цену

        public double ChangedCost
        {
            get
            {
                return Convert.ToInt64( ProductsCost ) - Convert.ToInt64(ProductsCost) * (ProductsDiscount / 100);
            }
        }

        public string ProductsArticle { get; set; }
        public string ProductsName { get; set; }
        public string ProductsMeasure { get; set; }
        public string ProductsCost { get; set; }
        public string ProductsSupplier { get; set; }
        public string ProductsProducer { get; set; }
        public string ProductsCategory { get; set; }
        public int ProductsDiscount { get; set; }
        public int ProductsCountOnInventory { get; set; }
        public string ProductsDescription { get; set; }
        public string ProductsPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
    }
}
